[package]
name = "day6"
version = "0.1.0"
edition = "2018"

[dependencies]
failure = "0.1.3"
strum = "0.11.0"
strum_macros = "0.11.0"
rayon = "1"

regex = "0.2"

itertools = "0.7.11"

[dev-dependencies]
assert_cli = "0.5"
